mutation {
    addPond(
        pondData: {
            title: "sample"
            description: "sample --------------------------------------"
            opts: ["opts1", "opts2"]
        }
    ) {
        id
        title
        description
        creationDate
        opts
    }
}

query {
    ponds {
        id
        title
        description
        creationDate
        opts
    }
}
